### ISSUE TITLE
Uncaught TypeError: fs.lstat is not a function

### ISSUE THREAD

**Issue by ikeafurniture** [ikeafurniture/orfs#6]
Steps to reproduce:

1) Click on box and upload a file.
2) View console.

Seems to be an error in the glob subdependency (glob.js:716). But why is it happening in this project and not a simple test script?

**Comment by ikeafurniture** [comment]
Was a problem with browserify and native node modules.

**Comment by fazo96** [comment]
hey, how'd you fixed this? :) I'm having the same problem

**Comment by ikeafurniture** [comment]
Hey fazo I found a solution here: https://github.com/substack/node-browserify/issues/1277

The problem was browserify is not bundling some native modules like fs. Or at least not exposing them with a global variable. 

Now, instead of running browserify from the command line, I use a custom build script which inserts the fs global variable: https://github.com/ikeafurniture/orfs/blob/master/build.js

Let me know if that works or if I need to clarify something!
